[package]
name = "zewif-zcashd"
version = "0.1.0"
edition = "2024"

[dependencies]
zewif = "0.1.0"
anyhow = "1.0.95"
bitflags = "2"
chrono = "0.4.39"
hex = "0.4.3"
sha2 = "^0.10.6"
ripemd = "0.1.3"
byteorder = "1.5.0"
uuid = "1.1"

# The following dependencies are chosen to exactly match those for `zcashd
# 0.6.2` and should not be updated unless `zcashd` updates its dependency
# versions. This crate exists expressly for deserialization of `zcashd`
# `wallet.dat` encoded data, so these must be kept in sync.
zcash_address = "0.6"
zcash_encoding = "0.2"
zcash_keys = { version = "0.4", features = ["transparent-inputs", "sapling", "orchard"] }
zcash_primitives = "0.19"
zcash_protocol = "0.4"
zip32 = "0.1"
orchard = "0.10"
sapling = { package = "sapling-crypto", version = "0.3", features = ["temporary-zcashd"] }
incrementalmerkletree = "0.7"
bridgetree = "0.6"

[dev-dependencies]
bc-rand = "^0.4.0"

[features]
default = []
with-context = []

[patch.crates-io]
zewif = { git = "https://github.com/nuttycom/zewif.git", rev = "9514ce42e0e8dd9a863359134bba621fd7065b45" }
